### ISSUE TITLE
can we: Block message, no sound alert, but still have a special info on statusbar

### ISSUE THREAD

**Issue by catscarlet** [loolooyyyy/qksms#2]
Hey sir, can you make your package works as this:
"Block message, no sound alert, but still have a special info on statusbar"

Cause most annoying SMS is sent by useful companies. I would check if there would be some important message got blocked by accident.

**Comment by loolooyyyy** [comment]
my laptop's stolen my friend. I can't do. anything actually. when I get a new one I'll let you know. 

read this :
https://github.com/loolooyyyy/qksms/issues/1

**Comment by catscarlet** [comment]
OK, thanks.
